### ISSUE TITLE
not working in FlatList

### ISSUE THREAD

**Issue by alz10** [WrathChaos/react-native-animated-component#1]
https://snack.expo.io/zRQ!I59FD

**Comment by kuraydev** [comment]
Hello @alz10,
Yes, it is not directly working with FlatList because RNAnimated simply animate EVERY CHILD. It cannot reach or animate each FlatList render child. Therefore, we need another library just for animate FlatList and its components :) However, I could not find a direct way to reach or animate every FlatList child.
